# == Example and Default configs ==
# These are some default configs, You can override them with a >> configs.local.yml << file
# It won't be versioned
site_url:   "http://localhost:3000"
secret_token: "49d9a7008b73ca1cfc4e95a This is your Rails secret_token 0f86d3c5c9b3d6250b037bc2bdd16d03edb2ee86bf1"
twitter:
    key: "gTaolBdom3yFJnPSOlfJZw" # You should change this keys with your own
    secret: "ZH5z9KkVR74l8kpJaz0OcQiEwsgZlpNDdbfganLyw"
facebook:
    key: "199733406772763"        # You should change this keys with your own
    secret: "d2416a55b79f4be7eba5c10733be9a07"
